# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# .github/workflows/cd.yml
name: CD
# Run on main branch after CI workflow has completed on main.
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only go ahead with the job if CI completed successfully (i.e. tests passed).
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout project source
      - name: Checkout source
        uses: actions/checkout@v1
      # Install Node.js dependency
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      # Install package.json dependencies
      - name: Install
        run: yarn install
      
      # Run the production build - this runs: gatsby build
      # which generates the "public" directory containing the entire site.
      - name: Build
        run: yarn run build
      # Use a community action from the Actions Marketplace to deploy
      # the "public" directory generated by the build to Github Pages.
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.GITHUB_PAGES_TOKEN }}
          deploy-branch: github-pages

